# Build stage
FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests


# Tomcat stage
FROM tomcat:10.1-jdk17-temurin

# Remove default Tomcat applications
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy our WAR as ROOT application
COPY --from=build /app/target/OfficialWebsite.war \
    /usr/local/tomcat/webapps/ROOT.war

# Vercel uses PORT.
# If PORT is not provided, use 80.
CMD ["sh", "-c", "sed -i \"s/port=\\\"8080\\\"/port=\\\"${PORT:-80}\\\"/\" /usr/local/tomcat/conf/server.xml && catalina.sh run"]